apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-test-api-server
  labels:
    togomi: go-test-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      togomi: go-test-api-server
  template:
    metadata:
      name: go-test-api-server
      labels:
        togomi: go-test-api-server
    spec:
      containers:
        - name: go-test-api-server
          image: aldlfkahs/go-simple-api-server:latest
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: go-test-api-server-service 
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    togomi: go-test-api-server
  type: NodePort
